In [1]:
# Step 1: Import Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import LabelEncoder

In [9]:


# Step 2: Load Data
data = pd.read_csv('./datasets/sales_and_trends_df.csv')
data.head()

,bike_name,bike_type,date_ordered,quantity,search_value,bike_type_search_value
0,UrbanCommuter 500,Hybrid Bike,2022-05-14,1,61,61
1,UrbanCommuter 500,Hybrid Bike,2022-05-14,1,61,61
2,UrbanCommuter 500,Hybrid Bike,2022-05-14,1,61,64
3,UrbanCommuter 500,Hybrid Bike,2022-05-14,1,61,64
4,UrbanCommuter 500,Hybrid Bike,2022-05-14,1,61,64

In [10]:

# Step 3: Data Preprocessing
data['date_ordered'] = pd.to_datetime(data['date_ordered'])
data = data.sort_values(['bike_name', 'date_ordered'])  # Sort by product and date

# Step 4: Feature Engineering
# Extract time-based features
data['year'] = data['date_ordered'].dt.year
data['month'] = data['date_ordered'].dt.month
data['day'] = data['date_ordered'].dt.day
data['day_of_week'] = data['date_ordered'].dt.dayofweek

# Lag features for each product's previous quantity
data['quantity_lag1'] = data.groupby('bike_name')['quantity'].shift(1)
data['rolling_avg_7'] = data.groupby('bike_name')['quantity'].rolling(window=7).mean().reset_index(0, drop=True)

data['search_value_lag1'] = data.groupby('bike_name')['search_value'].shift(1)
data['bike_type_search_value_lag1'] = data.groupby('bike_name')['bike_type_search_value'].shift(1)

# Drop rows with NaN values from lag/rolling features
data = data.dropna()
data.head()

,bike_name,bike_type,date_ordered,quantity,search_value,bike_type_search_value,year,month,day,day_of_week,quantity_lag1,rolling_avg_7,search_value_lag1,bike_type_search_value_lag1
9498,Speedster Pro,Road Bike,2020-01-02,1,40,41,2020,1,2,3,1.0,1.0,40.0,41.0
132860,Speedster Pro,Road Bike,2020-01-04,1,40,40,2020,1,4,5,1.0,1.0,40.0,41.0
132861,Speedster Pro,Road Bike,2020-01-04,1,40,40,2020,1,4,5,1.0,1.0,40.0,40.0
132862,Speedster Pro,Road Bike,2020-01-04,1,40,41,2020,1,4,5,1.0,1.0,40.0,40.0
132863,Speedster Pro,Road Bike,2020-01-04,1,40,41,2020,1,4,5,1.0,1.0,40.0,41.0

In [11]:


# Step 6: Train-Test Split
data.to_csv('./datasets/processed_sales_df.csv', index=False)

In [12]:
print(data)

                bike_name    bike_type date_ordered  quantity  search_value  \
9498        Speedster Pro    Road Bike   2020-01-02         1            40
132860      Speedster Pro    Road Bike   2020-01-04         1            40
132861      Speedster Pro    Road Bike   2020-01-04         1            40
132862      Speedster Pro    Road Bike   2020-01-04         1            40
132863      Speedster Pro    Road Bike   2020-01-04         1            40
...                   ...          ...          ...       ...           ...
86375   UrbanCommuter 500  Hybrid Bike   2024-10-01         1            48
86376   UrbanCommuter 500  Hybrid Bike   2024-10-01         1            48
86377   UrbanCommuter 500  Hybrid Bike   2024-10-01         1            48
86378   UrbanCommuter 500  Hybrid Bike   2024-10-01         1            48
86379   UrbanCommuter 500  Hybrid Bike   2024-10-01         1            48

        bike_type_search_value  year  month  day  day_of_week  quantity_lag1  \
9498                        41  2020      1    2            3            1.0
132860                      40  2020      1    4            5            1.0
132861                      40  2020      1    4            5            1.0
132862                      41  2020      1    4            5            1.0
132863                      41  2020      1    4            5            1.0
...                        ...   ...    ...  ...          ...            ...
86375                       48  2024     10    1            1            1.0
86376                       48  2024     10    1            1            1.0
86377                       48  2024     10    1            1            1.0
86378                       48  2024     10    1            1            1.0
86379                       46  2024     10    1            1            1.0

        rolling_avg_7  search_value_lag1  bike_type_search_value_lag1
9498              1.0               40.0                         41.0
132860            1.0               40.0                         41.0
132861            1.0               40.0                         40.0
132862            1.0               40.0                         40.0
132863            1.0               40.0                         41.0
...               ...                ...                          ...
86375             1.0               48.0                         48.0
86376             1.0               48.0                         48.0
86377             1.0               48.0                         48.0
86378             1.0               48.0                         48.0
86379             1.0               48.0                         48.0

[139952 rows x 14 columns]